/*
    This file is part of leafDrums.

    leafDrums is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    leafDrums is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with leafDrums.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef IDENTIFIERS_H
#define IDENTIFIERS_H

#define IDC_CONTROL_BASE 1000

#define IDC_CONTROL_PLAY		(IDC_CONTROL_BASE+	1)
#define IDC_CONTROL_NEW			(IDC_CONTROL_BASE+	2)
#define IDC_CONTROL_OPEN		(IDC_CONTROL_BASE+	3)
#define IDC_CONTROL_SAVE		(IDC_CONTROL_BASE+	4)
#define IDC_CONTROL_WRITE		(IDC_CONTROL_BASE+	5)
#define IDC_CONTROL_HELP		(IDC_CONTROL_BASE+	6)
#define IDC_CONTROL_QUIT 		(IDC_CONTROL_BASE+	7)
#define IDC_CONTROL_STOP		(IDC_CONTROL_BASE+	8)

#define IDC_CONTROL_LEVELSCROLL	(IDC_CONTROL_BASE+	100)


#define IDC_SONG_BASE 2000

#define IDC_SONG_LEVELENVELOPE	(IDC_SONG_BASE+		1)
#define IDC_SONG_LOOP			(IDC_SONG_BASE+		2)
#define IDC_SONG_INSERT			(IDC_SONG_BASE+		3)
#define IDC_SONG_DELETE			(IDC_SONG_BASE+		4)
#define IDC_SONG_SELECT			(IDC_SONG_BASE+		5)
#define IDC_SONG_PASTE			(IDC_SONG_BASE+		6)

#define IDC_SONG_TEMPOSPIN		(IDC_SONG_BASE+		10)

#define IDC_SONG_HSCROLL		(IDC_SONG_BASE+		20)
#define IDC_SONG_VSCROLL		(IDC_SONG_BASE+		21)

#define IDC_SONG_LEVELSCROLL0	(IDC_SONG_BASE+		100	)


#define IDC_PATTERN_BASE 3000

#define IDC_PATTERN_FINEGRID	(IDC_PATTERN_BASE+	1)
#define IDC_PATTERN_MAKETRIPLET	(IDC_PATTERN_BASE+	2)
#define IDC_PATTERN_DUPLICATE	(IDC_PATTERN_BASE+	3)
#define IDC_PATTERN_RENAME		(IDC_PATTERN_BASE+	4)
#define IDC_PATTERN_NAMEEDIT	(IDC_PATTERN_BASE+	5)
#define IDC_PATTERN_DELETE		(IDC_PATTERN_BASE+	6)
#define IDC_PATTERN_NEW			(IDC_PATTERN_BASE+	7)
#define IDC_PATTERN_ADDBEAT		(IDC_PATTERN_BASE+	8)
#define IDC_PATTERN_REMOVEBEAT	(IDC_PATTERN_BASE+	9)


#define IDC_PATTERN_SPIN		(IDC_PATTERN_BASE+	10)

#define IDC_PATTERN_HSCROLL		(IDC_PATTERN_BASE+	20)
#define IDC_PATTERN_VSCROLL		(IDC_PATTERN_BASE+	21)



#define IDC_SOUNDS_BASE 4000

#define IDC_SOUNDS_REFRESH		(IDC_SOUNDS_BASE+	1)
#define IDC_SOUNDS_OPTIONS		(IDC_SOUNDS_BASE+	2)
#define IDC_SOUNDS_SONG			(IDC_SOUNDS_BASE+	3)
#define IDC_SOUNDS_OPEN			(IDC_SOUNDS_BASE+	4)

#define IDC_SOUNDS_VSCROLL		(IDC_SOUNDS_BASE+	10)


#define IDC_AUDIO_BASE 5000

#define IDC_AUDIO_TESTORIGINAL	(IDC_AUDIO_BASE+		1)
#define IDC_AUDIO_TESTOUTPUT	(IDC_AUDIO_BASE+		2)
#define IDC_AUDIO_PRESETOPEN	(IDC_AUDIO_BASE+		3)
#define IDC_AUDIO_PRESETSAVE	(IDC_AUDIO_BASE+		4)
#define IDC_AUDIO_SONG			(IDC_AUDIO_BASE+		5)

#define IDC_AUDIO_ENVELOPE		(IDC_AUDIO_BASE+		10)
#define IDC_AUDIO_STRETCH		(IDC_AUDIO_BASE+		11)
#define IDC_AUDIO_TUNING		(IDC_AUDIO_BASE+		12)
#define IDC_AUDIO_REVERSE		(IDC_AUDIO_BASE+		13)

#define IDC_AUDIO_E_SKIP		(IDC_AUDIO_BASE+		20)
#define IDC_AUDIO_E_LENGTH		(IDC_AUDIO_BASE+		21)
#define IDC_AUDIO_E_ATTACK		(IDC_AUDIO_BASE+		22)
#define IDC_AUDIO_E_DECAY		(IDC_AUDIO_BASE+		23)

#define IDC_AUDIO_S_TOTAL		(IDC_AUDIO_BASE+		30)
#define IDC_AUDIO_S_SKIP		(IDC_AUDIO_BASE+		31)
#define IDC_AUDIO_S_LENGTH		(IDC_AUDIO_BASE+		33)

#define IDC_AUDIO_T_DIRECTION	(IDC_AUDIO_BASE+		40)
#define IDC_AUDIO_T_OCTAVE		(IDC_AUDIO_BASE+		41)
#define IDC_AUDIO_T_SEMITONE	(IDC_AUDIO_BASE+		42)
#define IDC_AUDIO_T_FINETUNE	(IDC_AUDIO_BASE+		43)

#define IDC_AUDIO_ACCENTSCROLL	(IDC_AUDIO_BASE+		50)

#define IDC_AUDIO_FX1TYPE		(IDC_AUDIO_BASE+		60)
#define IDC_AUDIO_FX2TYPE		(IDC_AUDIO_BASE+		61)
#define IDC_AUDIO_FX1SNAP		(IDC_AUDIO_BASE+		62)
#define IDC_AUDIO_FX2SNAP		(IDC_AUDIO_BASE+		63)


#define IDC_AUDIO_FX1SCROLL0	(IDC_AUDIO_BASE+		100)
#define IDC_AUDIO_FX2SCROLL0	(IDC_AUDIO_BASE+		200)

#define IDC_AUDIO_FX1SPIN0		(IDC_AUDIO_BASE+		300)
#define IDC_AUDIO_FX2SPIN0		(IDC_AUDIO_BASE+		400)



#define IDC_DRUMS_BASE 6000

#define IDC_DRUMS_DRUM0			(IDC_DRUMS_BASE+		1)

#define IDC_DRUMS_LEVELSCROLL0	(IDC_DRUMS_BASE+		100)
#define IDC_DRUMS_PANSCROLL0	(IDC_DRUMS_BASE+		200)
#define IDC_DRUMS_MUTE0			(IDC_DRUMS_BASE+		300)



#define FIRSTCOMMAND IDC_CONTROL_BASE
#define LASTCOMMAND (IDC_CONTROL_BASE+10000)

#endif // IDENTIFIERS_H
